name: strangelove ictest

on: [push]

# Cancel task if a new commit is pushed while old workflows run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.19

jobs:
  e2e-setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install Go - no need since we do this later for ICtest
      # - name: Set up Go $GO_VERSION
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: $GO_VERSION

      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - name: Rust Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
          key: ${{ runner.os }}-cargo-with-artifacts-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build the artifact
        run: make compile

      # upload the artifact for future job use
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3        
        with:
          name: ${{ github.job }}-contracts
          retention-days: 1
          path: |
            artifacts
            !artifacts/*.txt

  test-basic:
    runs-on: ubuntu-latest
    needs: e2e-setup
    steps:
      - name: Set up Go $GO_VERSION
        uses: actions/setup-go@v3
        with:
          go-version: $GO_VERSION
        id: go

      - name: checkout chain
        uses: actions/checkout@v3        

      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.job }}-contracts
          path: contracts

      - run: make ictest-basic

  test-whitelist:
    runs-on: ubuntu-latest
    needs: e2e-setup
    steps:
      - name: Set up Go $GO_VERSION
        uses: actions/setup-go@v3
        with:
          go-version: $GO_VERSION
        id: go

      - name: checkout chain
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.job }}-contracts
          path: contracts

      - run: make ictest-whitelist